# Generated by Django 5.2.17 on 2026-10-05 07:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=20000, verbose_name='текст решения')),
                ('solution_url', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator(schemes=('http', 'https'))], verbose_name='ссылка на решение')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='отправлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='задание')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='студент')),
            ],
            options={
                'verbose_name': 'решение',
                'verbose_name_plural': 'решения',
                'ordering': ('-submitted_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_student'), models.CheckConstraint(condition=models.Q(('answer', ''), ('solution_url', ''), _negated=True), name='submission_has_content')],
            },
        ),
    ]
