# Generated by Django 5.2.17 on 2026-10-05 09:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='балл')),
                ('feedback', models.TextField(blank=True, max_length=5000, verbose_name='обратная связь')),
                ('graded_at', models.DateTimeField(auto_now=True, verbose_name='проверено')),
                ('graded_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='given_grades', to=settings.AUTH_USER_MODEL, verbose_name='проверил')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='assignments.submission', verbose_name='решение')),
            ],
            options={
                'verbose_name': 'оценка',
                'verbose_name_plural': 'оценки',
                'ordering': ('-graded_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 1000)), name='grade_valid_score')],
            },
        ),
    ]
