# Generated by Django 5.2.17 on 2026-10-05 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_grade'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course', 'status', 'due_at'], name='assign_course_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', '-submitted_at', '-id'], name='sub_assignment_time_idx'),
        ),
    ]
